/*
    File:
        AlignerSelectionDialog.java
 *
    Revision:
        1.0.0.1
 *
    Description:
        Shows the dialog allowing the user to select the aligner.
 *
    Project:
        GeneAnalyzer 2.2
 *
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */

package algorithms.alignment;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import kernel.Main;
import plugin.classes.IAligner;


public class AlignerSelectionDialog extends javax.swing.JDialog
{
    public class Options
    {
        public IAligner aligner = null;
        public boolean bUseSim  = true;
    };

    private int index = -1;


    public AlignerSelectionDialog()
    {
        super((java.awt.Frame)null, true);
        initComponents();
        setLocationRelativeTo(null);
    }

    public Options getOptions(IAligner[] aligners)
    {
        DefaultListModel model = new DefaultListModel();
        for(IAligner al:aligners)
            model.addElement(al.getName());
        jlAligners.setModel(model);
        setVisible(true);
        if(index==-1)
            return null;
        else
        {
            Options opt = new Options();
            opt.aligner = aligners[index];
            opt.bUseSim = jcbSimilarNamesOnly.isSelected();
            return opt;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlAligners = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcbSimilarNamesOnly = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alignment algorithm");
        setModal(true);
        setResizable(false);

        jlAligners.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlAligners.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAlignersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlAligners);

        jLabel1.setText("Select an alignment algorithm from the list.");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jcbSimilarNamesOnly.setSelected(true);
        jcbSimilarNamesOnly.setText("<html>Only fuse genes with similar names, e.g. CG1101A and<br>CG1101B.</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbSimilarNamesOnly)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbSimilarNamesOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        index = -1;
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = jlAligners.getSelectedIndex();
        if(i==-1)
        {
            JOptionPane.showMessageDialog(null, "Please, select an alignment algorithm", Main.APPTITLE, JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
            index = i;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jlAlignersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAlignersMouseClicked
        if(evt.getClickCount()==2)
        {
            int i = jlAligners.getSelectedIndex();
            if(i==-1)
                return;
            index = i;
            setVisible(false);
        }
    }//GEN-LAST:event_jlAlignersMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbSimilarNamesOnly;
    private javax.swing.JList jlAligners;
    // End of variables declaration//GEN-END:variables

}
