/*
    File:
        OptionsDialog.java
 *
    Revision:
        1.0.0.1
 *
    Description:
        Allows the user to select options for performing the analysis.
 *
    Project:
        GeneAnalyzer 2.2
 *
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */


package builtin.analyses.indel;

import bio.gene.GeneRegion;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class OptionsDialog extends javax.swing.JDialog
{
    private AnalysisOptions ao = null;
    
    public OptionsDialog(String[] pops, String[] regs)
    {
        super((java.awt.Frame)null, true);
        initComponents();
        setLocationRelativeTo(null);
        // Add populations.
        for(String s:pops)
        {
            jcPop.addItem(s);
            jcOut.addItem(s);
            jcDist.addItem(s);
        }
        // Add the regions names skipping the coding regions.
        for(String s:regs)
        {       
            if(s.equalsIgnoreCase(GeneRegion.EXON) || s.equalsIgnoreCase(GeneRegion.CDS))
                continue;
            jcbReg.addItem(s);
        }
        jcbReg.setSelectedIndex(0);
    }

    /**
     *  Displays the dialog and returns the options.
     *
     *  @param ao
     */
    public AnalysisOptions getOptions()
    {
        setVisible(true);
        return ao;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcPop = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcOut = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jcDist = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jcbMaxLen = new javax.swing.JCheckBox();
        jcbMinLen = new javax.swing.JCheckBox();
        jeMaxLen = new javax.swing.JTextField();
        jeMinLen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbReg = new javax.swing.JComboBox();
        jcbLimit = new javax.swing.JCheckBox();
        jeLimit = new javax.swing.JTextField();
        jrbLengthRange = new javax.swing.JRadioButton();
        jrbLengthUngapped = new javax.swing.JRadioButton();
        jcbCombine = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jeFilename = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jcbShow = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("InDels analysis options");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel2.setText("Population of interest:");
        jLabel2.setFocusable(false);

        jLabel3.setText("Outgroup:");
        jLabel3.setFocusable(false);

        jLabel6.setText("More distant group:");
        jLabel6.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcOut, 0, 172, Short.MAX_VALUE)
                            .addComponent(jcPop, 0, 172, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(jcDist, 0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jcDist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Region"));
        jPanel3.setMaximumSize(new java.awt.Dimension(369, 364));
        jPanel3.setMinimumSize(new java.awt.Dimension(369, 364));

        jcbMaxLen.setText("Maximal length:");
        jcbMaxLen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMaxLenItemStateChanged(evt);
            }
        });

        jcbMinLen.setText("Minimal length:");
        jcbMinLen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMinLenItemStateChanged(evt);
            }
        });

        jeMaxLen.setEnabled(false);
        jeMaxLen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jeMaxLenKeyTyped(evt);
            }
        });

        jeMinLen.setEnabled(false);
        jeMinLen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jeMinLenKeyTyped(evt);
            }
        });

        jLabel1.setText("Region type:");

        jcbLimit.setText("Limit the number of strains to");
        jcbLimit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLimitItemStateChanged(evt);
            }
        });

        jeLimit.setEnabled(false);
        jeLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jeLimitKeyTyped(evt);
            }
        });

        buttonGroup1.add(jrbLengthRange);
        jrbLengthRange.setSelected(true);
        jrbLengthRange.setText("The minimal and maximal length should fall into the range");
        jrbLengthRange.setEnabled(false);

        buttonGroup1.add(jrbLengthUngapped);
        jrbLengthUngapped.setText("Region length is the ungapped alignment length");
        jrbLengthUngapped.setEnabled(false);

        jcbCombine.setText("Combine multiple regions");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMaxLen)
                                    .addComponent(jcbMinLen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jeMinLen)
                                    .addComponent(jeMaxLen, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbReg, 0, 221, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbLengthRange)
                            .addComponent(jrbLengthUngapped)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jcbLimit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbCombine))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMaxLen)
                    .addComponent(jeMaxLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMinLen)
                    .addComponent(jeMinLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbLengthRange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbLengthUngapped)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCombine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbLimit)
                    .addComponent(jeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel2.setMaximumSize(new java.awt.Dimension(349, 124));
        jPanel2.setMinimumSize(new java.awt.Dimension(349, 124));

        jLabel4.setText("Output file:");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcbShow.setSelected(true);
        jcbShow.setText("Show results in a new window");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jcbShow))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jeFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3)
                    .addComponent(jeFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jcbShow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, 0, 325, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 325, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMaxLenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMaxLenItemStateChanged
        jeMaxLen.setEnabled(jcbMaxLen.isSelected()); 
        boolean enabled = (jcbMaxLen.isSelected() || jcbMinLen.isSelected());
        jrbLengthRange.setEnabled(enabled);
        jrbLengthUngapped.setEnabled(enabled);
}//GEN-LAST:event_jcbMaxLenItemStateChanged

    private void jcbMinLenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMinLenItemStateChanged
        jeMinLen.setEnabled(jcbMinLen.isSelected());
        boolean enabled = (jcbMaxLen.isSelected() || jcbMinLen.isSelected());
        jrbLengthRange.setEnabled(enabled);
        jrbLengthUngapped.setEnabled(enabled);
}//GEN-LAST:event_jcbMinLenItemStateChanged

    private void jeMaxLenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeMaxLenKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
            evt.setKeyChar('\0');
}//GEN-LAST:event_jeMaxLenKeyTyped

    private void jeMinLenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeMinLenKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
            evt.setKeyChar('\0');
}//GEN-LAST:event_jeMinLenKeyTyped

    private void jcbLimitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLimitItemStateChanged
        jeLimit.setEnabled(jcbLimit.isSelected());
}//GEN-LAST:event_jcbLimitItemStateChanged

    private void jeLimitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeLimitKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
            evt.setKeyChar('\0');
}//GEN-LAST:event_jeLimitKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Tab-separated text", "txt"));
        if (fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION)
           jeFilename.setText(fc.getSelectedFile().getAbsolutePath());
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ao = new AnalysisOptions();
        // Check whether the output file is set.
        if(!jeFilename.getText().isEmpty())
            ao.strOutput = jeFilename.getText();
        else if(!jcbShow.isSelected())
        {
            JOptionPane.showMessageDialog(null,
                                          "You must either specify an output file or check the box under\n" +
                                          "the file name field to display the result in a new window",
                                          "InDels analysis",
                                          JOptionPane.ERROR_MESSAGE);
            return;
        }
        ao.bShowRes = jcbShow.isSelected();
        // Populations.
        ao.strPop = (String)jcPop.getSelectedItem();
        ao.strOut = (String)jcOut.getSelectedItem();
        ao.strDist= (String)jcDist.getSelectedItem();
        ao.bCombine = jcbCombine.isSelected();
        // Type.
        ao.strType = (String)jcbReg.getSelectedItem();
        // Lengths.
        if(jcbMaxLen.isSelected() && !jeMaxLen.getText().isEmpty())
            ao.maxlen = Integer.parseInt(jeMaxLen.getText());
        else
            ao.maxlen = Integer.MAX_VALUE;
        if(jcbMinLen.isSelected() && !jeMinLen.getText().isEmpty())
            ao.minlen = Integer.parseInt(jeMinLen.getText());
        else
            ao.minlen = 0;
        // Correct if the maximal length is less than the minimal.
        if(ao.maxlen<ao.minlen)
        {
            int tmp = ao.maxlen;
            ao.maxlen = ao.minlen;
            ao.minlen = tmp;
        }
        // Max. strains.
        if(jcbLimit.isSelected() && !jeLimit.getText().isEmpty())
            ao.maxstr = Integer.parseInt(jeLimit.getText());
        else
            ao.maxstr = Integer.MAX_VALUE;
        ao.bLenRange = jrbLengthRange.isSelected();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ao = null;
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox jcDist;
    private javax.swing.JComboBox jcOut;
    private javax.swing.JComboBox jcPop;
    private javax.swing.JCheckBox jcbCombine;
    private javax.swing.JCheckBox jcbLimit;
    private javax.swing.JCheckBox jcbMaxLen;
    private javax.swing.JCheckBox jcbMinLen;
    private javax.swing.JComboBox jcbReg;
    private javax.swing.JCheckBox jcbShow;
    private javax.swing.JTextField jeFilename;
    private javax.swing.JTextField jeLimit;
    private javax.swing.JTextField jeMaxLen;
    private javax.swing.JTextField jeMinLen;
    private javax.swing.JRadioButton jrbLengthRange;
    private javax.swing.JRadioButton jrbLengthUngapped;
    // End of variables declaration//GEN-END:variables

}
