/*
    File:
        ViewerDialog.java
 *
    Revision:
        1.0.0.1
 *
    Description:
        GeneEntry viewer.

 *
    Project:
        GeneAnalyzer 2.2
 *
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */

package gui.gene;

import gui.editor.*;
import bio.gene.GeneEntry;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JDialog;


public class ViewerDialog extends JDialog
{
    private class Header extends JComponent
    {
        private final int OFFSET_TOP = 10;

        public Header(HeaderRenderer hr)
        {
            hr.setBounds(0, OFFSET_TOP, hr.getWidth(), hr.getHeight());
            this.add(hr);
            this.setPreferredSize(new Dimension(hr.getWidth(), hr.getHeight()));
        }
    };
    
    private EditorPanel ep = null;
    

    public ViewerDialog()
    {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setResizable(true);
    }
    
    public void showGeneEntry(GeneEntry ge)
    {
        setTitle(ge.getCommonName());
        ep = new EditorPanel();
        ep.displayAnnotation(ge);
        jspAlignment.setViewportView(ep);
        jspAlignment.setRowHeaderView(new Header(new HeaderRenderer(ge)));
        setVisible(true);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jspAlignment = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jtbShowAll = new javax.swing.JToggleButton();
        jtbMask = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jtbHighlightRegs = new javax.swing.JToggleButton();

        setTitle("Editor");

        jspAlignment.setBackground(new java.awt.Color(255, 255, 255));
        jspAlignment.setBorder(null);
        jspAlignment.setForeground(new java.awt.Color(255, 255, 255));
        jspAlignment.setDoubleBuffered(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonGroup1.add(jtbShowAll);
        jtbShowAll.setSelected(true);
        jtbShowAll.setText("Show all bases");
        jtbShowAll.setFocusable(false);
        jtbShowAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbShowAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbShowAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbShowAllItemStateChanged(evt);
            }
        });
        jToolBar1.add(jtbShowAll);

        buttonGroup1.add(jtbMask);
        jtbMask.setText("Mask identical bases");
        jtbMask.setFocusable(false);
        jtbMask.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbMask.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jtbMask);
        jToolBar1.add(jSeparator1);

        jtbHighlightRegs.setSelected(true);
        jtbHighlightRegs.setText("Highlight regions");
        jtbHighlightRegs.setFocusable(false);
        jtbHighlightRegs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtbHighlightRegs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHighlightRegs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbHighlightRegsItemStateChanged(evt);
            }
        });
        jToolBar1.add(jtbHighlightRegs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addComponent(jspAlignment, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAlignment, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtbShowAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbShowAllItemStateChanged
    if(ep!=null)
    {
        if(jtbShowAll.isSelected())
            ep.setDisplayMode(EditorPanel.SM_ALL);
        else
            ep.setDisplayMode(EditorPanel.SM_NO_IDENT);
    }
}//GEN-LAST:event_jtbShowAllItemStateChanged

private void jtbHighlightRegsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbHighlightRegsItemStateChanged
    if(ep!=null)
    {
        int mask = 0;
        if(jtbHighlightRegs.isSelected())
            mask = EditorPanel.HM_REGIONS;
        ep.setHighlightMask(mask);
    }
}//GEN-LAST:event_jtbHighlightRegsItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane jspAlignment;
    private javax.swing.JToggleButton jtbHighlightRegs;
    private javax.swing.JToggleButton jtbMask;
    private javax.swing.JToggleButton jtbShowAll;
    // End of variables declaration//GEN-END:variables

}
