/*
    File:
        CoverageDetails.java
 *
    Revision:
        1.0.0.1
 *
    Description:
        Displays the coverage histogram of the dataset.
 *
    Project:
        GeneAnalyzer 2.2
 *
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */

package gui;

import algorithms.Coverage;
import javax.swing.table.DefaultTableModel;


public class CoverageDetails extends javax.swing.JFrame 
{
    public CoverageDetails() 
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void displayCoverage(Coverage coverage)
    {         
        DefaultTableModel model = (DefaultTableModel)lvCoverage.getModel();
        model.setRowCount(0);
        int[] counts = coverage.getCounts();
        int l = coverage.getTotalLength();
        model.addRow(new Object[]{Integer.toString(l),
                                  Integer.toString(counts[0]),
                                  Integer.toString(counts[1]),
                                  Integer.toString(counts[2]),
                                  Integer.toString(counts[3]),
                                  Integer.toString(counts[4]),
                                  Integer.toString(counts[5]),
                                  Integer.toString(counts[6]),
                                  Integer.toString(counts[7]),
                                  Integer.toString(counts[8]),
                                  Integer.toString(counts[9])});
        setVisible(true);
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lvCoverage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lvCoverage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Length", "0-10%", "10-20%", "20-30%", "30-40%", "40-50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lvCoverage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lvCoverage;
    // End of variables declaration//GEN-END:variables

}
