/*
    File:
        SettingsDlg.java
 *   
    Revision:
        1.0.0.1
 * 
    Description:
        Allows the user to change the program settings.
 * 
    Project:
        GeneAnalyzer 2.2
 * 
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */

package gui;

import javax.swing.JOptionPane;
import kernel.Kernel;
import kernel.Main;
import kernel.SettingsManager;

public class SettingsDlg extends javax.swing.JDialog 
{
    private SettingsManager sm = null;

    public SettingsDlg(Kernel kernel) 
    {
        super((java.awt.Frame)null, true);
        initComponents();
        setLocationRelativeTo(null);
        sm = kernel.getInitializationData().sm;
        String[] ct = kernel.listCodonTables();
        int iIndex = -1;
        String strCT = sm.getSetting("", SettingsManager.CODONTABLE);
        for(int i=0;i<ct.length;i++)
        {
            jcbTables.addItem(ct[i]);
            if(strCT!=null && ct[i].equals(strCT))
                iIndex = i;
        }        
        if(iIndex>-1)
            jcbTables.setSelectedIndex(iIndex);
        // Code.
        String strCode = sm.getSetting("", SettingsManager.CODETYPE);
        if(strCode==null || strCode.equalsIgnoreCase(SettingsManager.CT_SIMPLE))
            jrbSimple.setSelected(true);
        else if(strCode.equalsIgnoreCase(SettingsManager.CT_EXTENDED))
            jrbExtended.setSelected(true);
        else
            jrbComplete.setSelected(true);
        // Locale.
        String strLocale = sm.getSetting("", SettingsManager.LOCALE);
        if(strLocale==null || strLocale.equalsIgnoreCase("Germany"))
            jcbLocale.setSelectedIndex(0);
        else
            jcbLocale.setSelectedIndex(1);
        // Heap space.
        String strHeap = sm.getSetting("", SettingsManager.HEAPSIZE);
        if(strHeap!=null && strHeap.matches("[0-9]+"))
        {
            jcbHeap.setSelected(true);
            jeHeap.setText(strHeap);
            jeHeap.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbTables = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jrbSimple = new javax.swing.JRadioButton();
        jrbExtended = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jcbLocale = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jrbComplete = new javax.swing.JRadioButton();
        jcbHeap = new javax.swing.JCheckBox();
        jeHeap = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setResizable(false);

        jLabel1.setText("Codons table:");

        jLabel2.setText("Allowed nucleotide code:");

        buttonGroup1.add(jrbSimple);
        jrbSimple.setSelected(true);
        jrbSimple.setText("Simple (A, C, G, T and '-' only)");

        buttonGroup1.add(jrbExtended);
        jrbExtended.setText("Extended (A, C, G, T, -, X, N)");

        jLabel3.setText("Locale (e.g. for decimal separator):");

        jcbLocale.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Germany", "US/UK" }));

        buttonGroup1.add(jrbComplete);
        jrbComplete.setText("Complete (A, C, G, T, -, X, N, S, W, R, Y, K, M, B, V, H, D, U)");

        jcbHeap.setText("Custom heap space (in MB):");
        jcbHeap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbHeapItemStateChanged(evt);
            }
        });

        jeHeap.setEnabled(false);
        jeHeap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jeHeapKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTables, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbExtended)
                            .addComponent(jrbSimple)
                            .addComponent(jrbComplete)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jcbHeap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jeHeap, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jcbLocale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbExtended)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbComplete)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbLocale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbHeap)
                    .addComponent(jeHeap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(jcbHeap.isSelected())
    {
        if(jeHeap.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Set the heap space size", 
                                          Main.APPTITLE, JOptionPane.ERROR_MESSAGE);
            return;
        }
        sm.addSetting("", SettingsManager.HEAPSIZE, jeHeap.getText());
    }
    else
        sm.removeSetting("", SettingsManager.HEAPSIZE);
    sm.addSetting("", SettingsManager.CODONTABLE, (String)jcbTables.getSelectedItem());
    if(jrbSimple.isSelected())
        sm.addSetting("", SettingsManager.CODETYPE, SettingsManager.CT_SIMPLE);
    else if(jrbExtended.isSelected())
        sm.addSetting("", SettingsManager.CODETYPE, SettingsManager.CT_EXTENDED);
    else
        sm.addSetting("", SettingsManager.CODETYPE, SettingsManager.CT_COMPLETE);
    sm.addSetting("", SettingsManager.LOCALE, (jcbLocale.getSelectedIndex()==0) ? "Germany" : "US");    
    setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jcbHeapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbHeapItemStateChanged
    jeHeap.setEnabled(jcbHeap.isSelected());
}//GEN-LAST:event_jcbHeapItemStateChanged

private void jeHeapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeHeapKeyTyped
    if(!Character.isDigit(evt.getKeyChar()))
        evt.setKeyChar('\0');
}//GEN-LAST:event_jeHeapKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcbHeap;
    private javax.swing.JComboBox jcbLocale;
    private javax.swing.JComboBox jcbTables;
    private javax.swing.JTextField jeHeap;
    private javax.swing.JRadioButton jrbComplete;
    private javax.swing.JRadioButton jrbExtended;
    private javax.swing.JRadioButton jrbSimple;
    // End of variables declaration//GEN-END:variables

}
