/*
    File:
        OptionsDialog.java
 *   
    Revision:
        1.0.0.1
 * 
    Description:
        Allows the user to specify the minimal quality level.
 * 
    Project:
        GeneAnalyzer 2.2
 * 
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */

package builtin.filters.quality;

import kernel.QualityChecker;


public class OptionsDialog extends javax.swing.JDialog 
{
    int iLevel = -1;

    public OptionsDialog() 
    {
        super((java.awt.Frame)null, true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public int getLevel()
    {
        setVisible(true);
        return iLevel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jrbLevel0 = new javax.swing.JRadioButton();
        jrbLevel1 = new javax.swing.JRadioButton();
        jrbLevel3 = new javax.swing.JRadioButton();
        jrbLevel4 = new javax.swing.JRadioButton();
        jrbLevel2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quality level filter");
        setResizable(false);

        jLabel1.setText("Specify the minimal quality level.");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbLevel0);
        jrbLevel0.setText("Level 0 (no problems)");

        buttonGroup1.add(jrbLevel1);
        jrbLevel1.setSelected(true);
        jrbLevel1.setText("Level 1 (negligible errors)");

        buttonGroup1.add(jrbLevel3);
        jrbLevel3.setText("Level 3 (premature terminal codon)");

        buttonGroup1.add(jrbLevel4);
        jrbLevel4.setText("Level 4 (severe deficits)");

        jrbLevel2.setText("Level 2 (invalid ORF)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbLevel1)
                            .addComponent(jrbLevel0)
                            .addComponent(jrbLevel2)
                            .addComponent(jrbLevel3)
                            .addComponent(jrbLevel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbLevel0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbLevel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbLevel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbLevel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbLevel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    iLevel = -1;
    setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(jrbLevel0.isSelected())
        iLevel = QualityChecker.QUALITY_LEVEL_0;
    if(jrbLevel1.isSelected())
        iLevel = QualityChecker.QUALITY_LEVEL_1;
    if(jrbLevel2.isSelected())
        iLevel = QualityChecker.QUALITY_LEVEL_2;
    if(jrbLevel3.isSelected())
        iLevel = QualityChecker.QUALITY_LEVEL_3;
    if(jrbLevel4.isSelected())
        iLevel = QualityChecker.QUALITY_LEVEL_4;
    setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jrbLevel0;
    private javax.swing.JRadioButton jrbLevel1;
    private javax.swing.JRadioButton jrbLevel2;
    private javax.swing.JRadioButton jrbLevel3;
    private javax.swing.JRadioButton jrbLevel4;
    // End of variables declaration//GEN-END:variables

}
