/*
    File:
        SplashScreen.java
 *
    Revision:
        1.0.0.1
 *
    Description:
        Displays a splash dialog while application is starting.
 *
    Project:
        GeneAnalyzer 2.2
 *
    Copyright:
        (c) 2008. Sergej Nowoshilow, Biozentrum, Martinsried, Germany.
 */
package gui.splash;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;


public class SplashScreen extends javax.swing.JDialog 
{
    public SplashScreen() 
    {
        super((java.awt.Frame)null, false);
        initComponents();
        setLocationRelativeTo(null);
        setLayout(new GridLayout(1, 1));
        add(new SplashPanel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(480, 300));
        setResizable(false);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    /***************************************************************************
    *                       PRIVATE CLASSES                                    *
    ***************************************************************************/
    private class SplashPanel extends JPanel
    {
        private BufferedImage img = null;
        
        public SplashPanel()
        {
            URL imgURL = getClass().getResource("/img/splash.png");
            try
            {
                if(imgURL!=null)
                {
                    img = ImageIO.read(imgURL);
                }
            } 
            catch (IOException ex)
            {}
        }
        
        @Override
        public void paintComponent(Graphics g) 
        {
            g.drawImage(img, 0, 0, null);
        }

    };
}
